### ISSUE TITLE
Change example 2 (Modal) to use the <dialog> element instead of <div>

### ISSUE THREAD

**Issue by AJ-Kulundu** [gathuku/hotwiredcases#29]
The `<dialog>` element is now supported on all browsers [check here](https://caniuse.com/dialog).

It provides the following benefits:
1.  Shorter syntax:  `<dialog open></dialog>` is the same as `<div role="dialog" aria-modal="true"></div>` 
2.  `<form>` elements can close a `<dialog>` if they have the attribute `method="dialog"` or if the button used to submit the form has `formmethod="dialog"`
3. It has a `::backdrop` pseudo element to style the backdrop of the modal.

**Comment by gathuku** [comment]
Thank for opening this @AJ-Kulundu
