### ISSUE TITLE
Confirm subscriber email.

### ISSUE THREAD

**Issue by gathuku** [gathuku/hotwiredcases#6]
I want to confirm/verify a subscriber email. 

- Add `confirmed_at:datetime` to `Subscriber`
- Add new mailer `SubcriberMailer`?
- Send a link to confirm  using signed global id(`subscriber.to_sgid.to_s`)
- Update `confirmed_at` when link is clicked
- Setup production email delivery using Postmark

**Comment by aquilarafa** [comment]
I can contribute ✋ .

**Comment by gathuku** [comment]
> I can contribute ✋ .

@aquilarafa Thank you. I have assigned to you.

**Comment by mwaurajr** [comment]
I can contribute too ☺️.

**Comment by gathuku** [comment]
> I can contribute too ☺️.

@mwaurajr please work on this https://github.com/gathuku/hotwiredcases/issues/7

**Comment by aquilarafa** [comment]
#8 Started coding today.
