### ISSUE TITLE
Validate product description on example 1 and avoid persisting change to database

### ISSUE THREAD

**Issue by gathuku** [gathuku/hotwiredcases#7]
If you look at example 1 (https://hotwiredcases.dev/examples/1) currently someone updated the descriptions with and empty test. 
This is how it looked like before.

<img width="500" alt="Screen Shot 2023-06-09 at 7 20 07 PM" src="https://github.com/gathuku/hotwiredcases/assets/26896865/ad516d29-bfc9-482f-909e-ad28038b323e">

A fix to this should adress: -

1. Validate description precense
2. Avoid persisting changes 
  I think we should check if the object is valid and redirect else render edit page to show errors at this level
  https://github.com/gathuku/hotwiredcases/blob/da748e352bc4e0f0710c4c82ce6e27b5fd7d911b/app/controllers/e1/product_descriptions_controller.rb#L6-L10

**Comment by mwaurajr** [comment]
Done but can't push changes even in my own branch!!!! Kindly help out.

**Comment by gathuku** [comment]
> Done but can't push changes even in my own branch!!!! Kindly help out.

@mwaurajr Which issues are you having? You can include any error message.

**Comment by mwaurajr** [comment]
No it's done kindly check the PR

**Comment by gathuku** [comment]
> No it's done kindly check the PR

@mwaurajr Looked at the PR and it's doesn't have anything , only a ruby version change.

**Comment by mwaurajr** [comment]
#9 
has three commits!!!
